# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestQ2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_q2(self):
    # Test name: Q2
    # Step # | name | target | value
    # 1 | open | https://tutorialsninja.com/demo/ | 
    self.driver.get("https://tutorialsninja.com/demo/")
    # 2 | setWindowSize | 1280x672 | 
    self.driver.set_window_size(1280, 672)
    # 3 | click | id=top-links | 
    self.driver.find_element(By.ID, "top-links").click()
    # 4 | click | css=.dropdown .hidden-xs | 
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown .hidden-xs").click()
    # 5 | click | linkText=Login | 
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    # 6 | click | id=input-email | 
    self.driver.find_element(By.ID, "input-email").click()
    # 7 | type | id=input-email | sreebhargavreddy@gmail.com
    self.driver.find_element(By.ID, "input-email").send_keys("sreebhargavreddy@gmail.com")
    # 8 | click | id=input-password | 
    self.driver.find_element(By.ID, "input-password").click()
    # 9 | type | id=input-password | Bhargav
    self.driver.find_element(By.ID, "input-password").send_keys("Bhargav")
    # 10 | click | css=.btn:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    # 11 | click | css=.list-inline > .dropdown | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-inline > .dropdown").click()
    # 12 | click | css=.dropdown .hidden-xs | 
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown .hidden-xs").click()
    # 13 | click | linkText=Logout | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    # 14 | close |  | 
    self.driver.close()
  
