[DEFAULT]
base_url = https://demowebshop.tricentis.com
browser = chrome
;browser = firefox
;browser = edge
implicit_wait = 5
explicit_wait = 10
test_data_path = data/users.csv
customer_info_url = /customer/info

